/**
 * Pull the podcast feed into src/data/podcast.json.
 *
 * Run by hand when there is a new episode: `npm run podcast:sync`.
 *
 * The feed is not read at build time on purpose. The symposium overlay
 * already establishes the rule -- the repository has to stand on its own --
 * and a nightly build that fails because anchor.fm is having a minute would
 * take the whole site down with it, for a podcast that publishes monthly.
 * A committed file also means the episode list is reviewable in a pull
 * request like everything else here.
 *
 * Deliberately not clever: no XML library, because the shape being read is
 * four fields per item from a feed generated by one host, and a dependency
 * for that is a dependency to keep updated.
 */
import { writeFileSync } from 'node:fs';

const FEED = 'https://anchor.fm/s/fe335014/podcast/rss';
const OUT = new URL('../src/data/podcast.json', import.meta.url).pathname;

/** Where else the show is listed. These are subscribe links, not players. */
const PLATFORMS = {
  spotify: 'https://open.spotify.com/show/7rA9IoDcI5ybW0Y4HQlmHq',
  apple: 'https://podcasts.apple.com/podcast/id1797656975',
  castbox: 'https://castbox.fm/channel/6480428',
  rss: FEED,
};

const cdata = (s: string): string => s.replace(/^<!\[CDATA\[/, '').replace(/\]\]>$/, '').trim();

function tag(source: string, name: string): string {
  const m = new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`).exec(source);
  return m ? cdata(m[1]) : '';
}

function attr(source: string, element: string, name: string): string {
  const m = new RegExp(`<${element}[^>]*\\s${name}="([^"]*)"`).exec(source);
  return m ? m[1] : '';
}

/** Entities, then tags, then collapse. Feed descriptions are HTML. */
function plainText(html: string): string {
  return html
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<\/p>/gi, ' ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

/** `itunes:duration` is HH:MM:SS, MM:SS, or already seconds. */
function durationSeconds(raw: string): number {
  if (!raw) return 0;
  if (/^\d+$/.test(raw)) return Number(raw);
  const parts = raw.split(':').map(Number);
  if (parts.some(Number.isNaN)) return 0;
  return parts.reduce((total, p) => total * 60 + p, 0);
}

const response = await fetch(FEED, { headers: { 'User-Agent': 'rsg-turkiye-website/1.0' } });
if (!response.ok) {
  console.error(`Feed returned ${response.status}. src/data/podcast.json left as it is.`);
  process.exit(1);
}
const xml = await response.text();

const channel = xml.slice(0, xml.indexOf('<item>'));
const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map((m) => m[1]);
if (items.length === 0) {
  console.error('Feed parsed to zero episodes, which is certainly wrong. Nothing written.');
  process.exit(1);
}

const episodes = items.map((item) => ({
  guid: tag(item, 'guid') || attr(item, 'enclosure', 'url'),
  title: tag(item, 'title'),
  // ISO, so the page can format it per language rather than shipping the
  // feed's RFC 822 English month names to a Turkish reader.
  pubDate: new Date(tag(item, 'pubDate')).toISOString(),
  durationSeconds: durationSeconds(tag(item, 'itunes:duration')),
  audioUrl: attr(item, 'enclosure', 'url'),
  audioBytes: Number(attr(item, 'enclosure', 'length')) || 0,
  image: attr(item, 'itunes:image', 'href'),
  description: plainText(tag(item, 'description')),
}));

const missing = episodes.filter((e) => !e.audioUrl || !e.title);
if (missing.length > 0) {
  console.error(`${missing.length} episode(s) have no audio or no title. Nothing written.`);
  process.exit(1);
}

const data = {
  // Recorded so a reader of the file knows how stale it might be.
  syncedAt: new Date().toISOString(),
  title: tag(channel, 'title'),
  description: plainText(tag(channel, 'description')),
  image: attr(channel, 'itunes:image', 'href'),
  platforms: PLATFORMS,
  episodes,
};

writeFileSync(OUT, `${JSON.stringify(data, null, 2)}\n`);
console.log(`${episodes.length} episode(s) written to src/data/podcast.json`);
for (const e of episodes) {
  console.log(`  ${e.pubDate.slice(0, 10)}  ${Math.round(e.durationSeconds / 60)} min  ${e.title}`);
}
